import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const ROOT_DIR = path.resolve(__dirname, '..');
const XML_PATH = path.join(ROOT_DIR, 'assets', 'colors.xml');
const OUTPUT_PATH = path.join(ROOT_DIR, 'src', 'color-map.ts');

function parseColorsXml(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const colorMap = {};
  
  // Regex to find <color name="name">#value</color>
  const regex = /<color name="([^"]+)">\s*(#[0-9A-Fa-f]+)\s*<\/color>/g;
  let match;
  
  while ((match = regex.exec(content)) !== null) {
    const name = match[1];
    let value = match[2].toUpperCase();
    
    // Normalize to #AARRGGBB
    if (value.length === 7) { // #RRGGBB
      value = '#FF' + value.substring(1);
    }
    
    // Store the FIRST name for a given hex value
    if (!colorMap[value]) {
      colorMap[value] = name;
    }
  }
  
  return colorMap;
}

function generateTsFile(colorMap) {
  const sortedEntries = Object.entries(colorMap).sort((a, b) => a[0].localeCompare(b[0]));
  
  const lines = [
    '// This file is auto-generated by scripts/generate-colors.mjs',
    '// Do not edit this file directly.',
    '',
    'export const COLOR_MAP: Record<string, string> = {',
  ];
  
  for (const [hex, name] of sortedEntries) {
    lines.push(`  '${hex}': '${name}',`);
  }
  
  lines.push('}');
  lines.push('');
  
  return lines.join('\n');
}

if (fs.existsSync(XML_PATH)) {
  console.log('Generating color map from:', XML_PATH);
  const map = parseColorsXml(XML_PATH);
  const tsContent = generateTsFile(map);
  fs.writeFileSync(OUTPUT_PATH, tsContent, 'utf-8');
  console.log('Successfully generated:', OUTPUT_PATH);
} else {
  console.error('Error: assets/colors.xml not found at', XML_PATH);
  process.exit(1);
}
